name: AI News Pipeline

on:
  schedule:
    - cron: '*/30 * * * *'  # Fetch articles every 30 minutes
    - cron: '0 17 * * *'    # Generate digest daily at 5 PM UTC
  workflow_dispatch:       # Manual trigger with task selection
    inputs:
      task:
        description: 'Select task to run'
        required: true
        default: 'fetch'
        type: choice
        options:
          - fetch
          - digest
          - both

concurrency:
  group: pipeline-${{ github.workflow }}-${{ github.job }}
  cancel-in-progress: false

jobs:
  fetch-articles:
    if: |
      (github.event_name == 'schedule' && github.event.schedule == '*/30 * * * *') ||
      (github.event_name == 'workflow_dispatch' && (github.event.inputs.task == 'fetch' || github.event.inputs.task == 'both'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run article fetch
        run: python scripts/fetch_articles.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMBEDDINGS_PROVIDER: gemini

  generate-digest:
    if: |
      (github.event_name == 'schedule' && github.event.schedule == '0 17 * * *') ||
      (github.event_name == 'workflow_dispatch' && (github.event.inputs.task == 'digest' || github.event.inputs.task == 'both'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run digest generation
        run: python scripts/generate_digest.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMBEDDINGS_PROVIDER: gemini
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}